### ISSUE TITLE
[meta] Preparação da infra para coleta de opinião da campanha

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#316]
- [ ] Criar uma conversa teste, com estereótipos e clusteres no django admin

- [ ] Criar uma nova missão e associar essa conversa a ela

- [ ] Ajustar o front do besouro, trocando o item de menu candidatos por missões e transformando a /inbox na home do app

- [ ] Testar a jornada de login, usuário acessando a partir de uma missão, incluindo recuperação de senha

- [ ] Testar os gatilhos automaticos de opinião (aceitar, comentar)

- [ ] Ver se o firebase está ativo em prod e inscrevendo novos assinantes

- [ ] Testar o push de admin com o link da missão e o push de opinião no canal da missão

- [ ] Verificar no banco se as opiniões estão sendo computadas

**Comment by ricardopoppi** [comment]
Questões percebidas no teste da jornada:

- [x] - Quando usuário acessa a tela da missão deslogado, via link, e é redirecionado para o login, o app "devolve" ele pra home do app e não pro link onde ele estava (missão)

- [x] - O gatilho de opinião foi concebido na conclusão da missão, era o que fazia sentido à época quando o foco era outras coisas e a coleta de opinião algo complementar. Como o foco agora é a coleta o gatinho teria que ser replicado também no ACEITE da missão

- [x] - Gatilho de opinião para novo comentário funcionando perfeitamente, sempre que o usuário comenta o card de opinião aparece e quando ele votou em todas não aparece mais

- [x] - Usuários que tinham aceitado receber push (firebase) em dev receberam a notificação de nova missão quando ela foi criada

- [x] - Como a notificação de opinião só é enviada a quem está no canal da missão, a divulgação nos mailings tem que ser do link da missão (um hack possível é add todo mundo no canal da missão antes de mandar, a ver...)

- [ ] - Em alguns testes, o push de opinião foi enviado corretamente para quem estava no canal da missão, em outros não, isso vai exigir debug melhor direto em prod pra um canal restrito aos nossos usuários

- [x] - O card de opinião está variando o tamanho conforme o tamanho do texto da frase, alterando a centralização do card e gerando desconforto (print)

- [x] - Já fiz algumas votações por usuários diferentes, precisamos verificar se o banco gravou essas opiniões corretamente




![captura de tela de 2018-11-28 11-56-07](https://user-images.githubusercontent.com/1162183/49158910-6b497980-f30a-11e8-85f6-a72b3f663420.png)

**Comment by ricardopoppi** [comment]
@davidCarlos três outros pontos:

- [x] - A opção esqueci minha senha informar qdo o usuário não tá na base ou tem login social "Esse email não está cadastrado. Você entrou no aplicativo via login social. Por favor clique em login via facebook para acessar novamente"

- [ ] - Vamos ter que cadastrar um novo texto de boas vinda no cadastro pois o atual fala dos candidatos:

```
Olá ,

Seu cadastro na plataforma online da campanha Unidos Contra a Corrupção foi efetivado com sucesso. Agora, basta acessar http://email.unidoscontraacorrupcao.org.br/c/eJx9jTsOwyAQBU9jl4hdA7ELCud3j4XFMVJi0BrfPy5SR3rVaDSPvVtYh9BnjxpGABxRm8kOCpS5zk7Po3nccHbD3XRGH1vmsseyNSGKReSokYoq8lJB-tWnBV0AfTEuMFC0TqNdgImMTRgm6N9-ba3u3TB3-DxHtar_UfGSIwmX8z5mJk6cPiUKtRP_pC8X2j_o para filtrar e conhecer as candidaturas que atendem aos três critérios da campanha:

1. Passado limpo;
2. Compromisso com a democracia; e
3. Apoio às Novas Medidas Contra a Corrupção.

Além de visualizar todas as candidatas e candidatos ao Congresso Nacional nestas eleições, você pode pressionar quem ainda não aderiu à campanha e conhecer detalhes importantes sobre as pessoas que querem nos representar pelos próximos quatro anos.

Se a candidata ou candidato em que você pretende votar ainda não se comprometeram com a campanha, este é o momento para mostrar sua voz e cobrar essa participação.

Vamos eleger parlamentares que se comprometem a trabalhar, desde o início de seu mandato, para discutir e aprovar as Novas Medidas contra a Corrupção!
```
@parrahenri ajuda a gente a escrever esse novo texto?

- [ ] - Vamos ter que apagar o display name de quem começa com "foo " ou "baz " ainda tem usuário assim na base (arquivo anexo dos que eu detectei pela exportação de 8/set: 

[display names para apagar os display names.txt](https://github.com/unidoscontraacorrupcao/ej-server/files/2626593/display.names.para.apagar.os.display.names.txt)

**Comment by ricardopoppi** [comment]
outro ponto

- Retirar o pedido para adicionar o app (pwa) pois login via facebook não funciona em pwa e esse e/será o principal meio de login

**Comment by davidCarlos** [comment]
Essas duas tarefas só podem ser resolvidas depois que fizermos o deploy em produção

- [ ] - Retirar o pedido para adicionar o app (pwa) pois login via facebook não funciona em pwa e esse e/será o principal meio de login

- [ ] - Vamos ter que apagar o display name de quem começa com "foo " ou "baz " ainda tem usuário assim na base (arquivo anexo dos que eu detectei pela exportação de 8/set:

**Comment by parrahenri** [comment]
Dando um feedback: enviei pra TI pedindo que formulem novo texto já que eles gostam de centralizar isso.
